import type {
  Amenity,
  Facility,
  Instruction,
  LatLng,
  Place,
  Report,
  Restriction,
  Route,
  TrafficZone,
  TruckClass,
} from "./types";
import { densify, pathLength } from "./geo";

export const ORIGIN: LatLng = { lat: 32.6892, lng: -96.8315 };
export const ORIGIN_LABEL = "I-35E & I-20";
export const ORIGIN_CITY = "Dallas, TX";

export const TRUCK_CLASSES: { id: TruckClass; label: string; blurb: string }[] = [
  { id: "semi", label: "Tractor-trailer", blurb: "53' dry van, 5 axles" },
  { id: "reefer", label: "Reefer", blurb: "Temperature-controlled" },
  { id: "flatbed", label: "Flatbed", blurb: "Open deck, straps & tarps" },
  { id: "tanker", label: "Tanker", blurb: "Liquid bulk" },
  { id: "box", label: "Box truck", blurb: "26' straight truck" },
];

export const PLACES: Place[] = [
  {
    id: "houston",
    name: "Houston",
    kind: "city",
    subtitle: "I-45 S · Port & ship channel",
    coord: { lat: 29.7604, lng: -95.3698 },
  },
  {
    id: "ftworth",
    name: "Fort Worth",
    kind: "city",
    subtitle: "I-30 W · Alliance corridor",
    coord: { lat: 32.7555, lng: -97.3308 },
  },
  {
    id: "austin",
    name: "Austin",
    kind: "city",
    subtitle: "I-35 S · Capitol region",
    coord: { lat: 30.2672, lng: -97.7431 },
  },
  {
    id: "okc",
    name: "Oklahoma City",
    kind: "city",
    subtitle: "I-35 N · I-40 crossroads",
    coord: { lat: 35.4676, lng: -97.5164 },
  },
  {
    id: "waco",
    name: "Waco",
    kind: "city",
    subtitle: "I-35 S · Mid-Texas",
    coord: { lat: 31.5493, lng: -97.1467 },
  },
  {
    id: "tyler",
    name: "Tyler",
    kind: "city",
    subtitle: "I-20 E · East Texas",
    coord: { lat: 32.3513, lng: -95.3011 },
  },
  {
    id: "shreveport",
    name: "Shreveport",
    kind: "city",
    subtitle: "I-20 E · Louisiana line",
    coord: { lat: 32.5252, lng: -93.7502 },
  },
  {
    id: "sanantonio",
    name: "San Antonio",
    kind: "city",
    subtitle: "I-35 S · I-10 westbound",
    coord: { lat: 29.4241, lng: -98.4936 },
  },
  {
    id: "alliance",
    name: "Alliance Intermodal",
    kind: "yard",
    subtitle: "BNSF · Haslet, TX",
    coord: { lat: 32.9765, lng: -97.318 },
  },
  {
    id: "lancaster-dc",
    name: "Lancaster Logistics Park",
    kind: "warehouse",
    subtitle: "I-20 / I-45 · South Dallas",
    coord: { lat: 32.592, lng: -96.756 },
  },
  {
    id: "houston-port",
    name: "Port of Houston",
    kind: "port",
    subtitle: "Barbours Cut · Bayport",
    coord: { lat: 29.737, lng: -95.021 },
  },
  {
    id: "dfw-cargo",
    name: "DFW Cargo East",
    kind: "warehouse",
    subtitle: "Air freight · Irving",
    coord: { lat: 32.896, lng: -97.038 },
  },
];

const A_FULL: Amenity[] = ["showers", "food", "scale", "def", "parking", "wifi"];
const A_STOP: Amenity[] = ["showers", "food", "def", "parking", "wifi"];
const A_REST: Amenity[] = ["parking", "wifi"];
const A_REPAIR: Amenity[] = ["showers", "food", "scale", "def", "parking", "wifi", "repair", "wash"];

export const FACILITIES: Facility[] = [
  {
    id: "loves-ennis",
    name: "Love's Travel Stop",
    subtitle: "Ennis · I-45 Exit 251",
    type: "truck_stop",
    coord: { lat: 32.329, lng: -96.625 },
    diesel: 3.41,
    def: 2.89,
    parking: { open: 8, total: 42 },
    amenities: A_FULL,
    rating: 4.5,
  },
  {
    id: "pilot-corsicana",
    name: "Pilot Flying J",
    subtitle: "Corsicana · I-45 Exit 231",
    type: "truck_stop",
    coord: { lat: 32.095, lng: -96.469 },
    diesel: 3.48,
    def: 2.94,
    parking: { open: 3, total: 64 },
    amenities: A_REPAIR,
    rating: 4.2,
  },
  {
    id: "ta-huntsville",
    name: "TA Travel Center",
    subtitle: "Huntsville · I-45 Exit 116",
    type: "truck_stop",
    coord: { lat: 30.724, lng: -95.551 },
    diesel: 3.36,
    def: 2.79,
    parking: { open: 14, total: 88 },
    amenities: A_REPAIR,
    rating: 4.4,
  },
  {
    id: "loves-madisonville",
    name: "Love's Travel Stop",
    subtitle: "Madisonville · I-45 Exit 142",
    type: "truck_stop",
    coord: { lat: 30.95, lng: -95.91 },
    diesel: 3.39,
    def: 2.85,
    parking: { open: 11, total: 50 },
    amenities: A_STOP,
    rating: 4.3,
  },
  {
    id: "petro-dallas",
    name: "Petro Stopping Center",
    subtitle: "Dallas South · I-20 Exit 467",
    type: "truck_stop",
    coord: { lat: 32.684, lng: -96.872 },
    diesel: 3.57,
    def: 2.99,
    parking: { open: 2, total: 96 },
    amenities: A_REPAIR,
    rating: 4.0,
  },
  {
    id: "pilot-west",
    name: "Pilot Flying J",
    subtitle: "Fort Worth West · I-30 Exit 7",
    type: "truck_stop",
    coord: { lat: 32.73, lng: -97.28 },
    diesel: 3.44,
    def: 2.91,
    parking: { open: 6, total: 54 },
    amenities: A_FULL,
    rating: 4.1,
  },
  {
    id: "loves-hillsboro",
    name: "Love's Travel Stop",
    subtitle: "Hillsboro · I-35 Exit 368",
    type: "truck_stop",
    coord: { lat: 32.011, lng: -97.115 },
    diesel: 3.33,
    def: 2.82,
    parking: { open: 19, total: 60 },
    amenities: A_FULL,
    rating: 4.6,
  },
  {
    id: "ta-waco",
    name: "TA Petro",
    subtitle: "Waco · I-35 Exit 330",
    type: "truck_stop",
    coord: { lat: 31.549, lng: -97.147 },
    diesel: 3.37,
    def: 2.84,
    parking: { open: 7, total: 72 },
    amenities: A_REPAIR,
    rating: 4.2,
  },
  {
    id: "pilot-temple",
    name: "Pilot Flying J",
    subtitle: "Temple · I-35 Exit 301",
    type: "truck_stop",
    coord: { lat: 31.098, lng: -97.343 },
    diesel: 3.45,
    def: 2.9,
    parking: { open: 4, total: 48 },
    amenities: A_STOP,
    rating: 4.0,
  },
  {
    id: "loves-georgetown",
    name: "Love's Travel Stop",
    subtitle: "Georgetown · I-35 Exit 261",
    type: "truck_stop",
    coord: { lat: 30.633, lng: -97.678 },
    diesel: 3.52,
    def: 2.97,
    parking: { open: 1, total: 40 },
    amenities: A_FULL,
    rating: 4.3,
  },
  {
    id: "loves-gainesville",
    name: "Love's Travel Stop",
    subtitle: "Gainesville · I-35 Exit 501",
    type: "truck_stop",
    coord: { lat: 33.626, lng: -97.133 },
    diesel: 3.35,
    def: 2.8,
    parking: { open: 16, total: 58 },
    amenities: A_FULL,
    rating: 4.5,
  },
  {
    id: "pilot-ardmore",
    name: "Pilot Flying J",
    subtitle: "Ardmore · I-35 Exit 29",
    type: "truck_stop",
    coord: { lat: 34.174, lng: -97.145 },
    diesel: 3.29,
    def: 2.76,
    parking: { open: 22, total: 80 },
    amenities: A_REPAIR,
    rating: 4.4,
  },
  {
    id: "loves-canton",
    name: "Love's Travel Stop",
    subtitle: "Canton · I-20 Exit 527",
    type: "truck_stop",
    coord: { lat: 32.556, lng: -95.863 },
    diesel: 3.4,
    def: 2.88,
    parking: { open: 9, total: 36 },
    amenities: A_STOP,
    rating: 4.2,
  },
  {
    id: "ta-longview",
    name: "TA Travel Center",
    subtitle: "Longview · I-20 Exit 589",
    type: "truck_stop",
    coord: { lat: 32.501, lng: -94.74 },
    diesel: 3.31,
    def: 2.81,
    parking: { open: 12, total: 70 },
    amenities: A_REPAIR,
    rating: 4.1,
  },
  {
    id: "rest-fairchild",
    name: "Fairchilds Creek Rest Area",
    subtitle: "I-45 S · MM 198 northbound too",
    type: "rest_area",
    coord: { lat: 31.72, lng: -96.17 },
    diesel: null,
    def: null,
    parking: { open: 18, total: 24 },
    amenities: A_REST,
    rating: 3.8,
  },
  {
    id: "rest-west",
    name: "West Rest Area",
    subtitle: "I-35 S · MM 353",
    type: "rest_area",
    coord: { lat: 31.8, lng: -97.09 },
    diesel: null,
    def: null,
    parking: { open: 5, total: 16 },
    amenities: A_REST,
    rating: 3.6,
  },
  {
    id: "rest-canton",
    name: "East Texas Rest Area",
    subtitle: "I-20 E · MM 540",
    type: "rest_area",
    coord: { lat: 32.54, lng: -95.7 },
    diesel: null,
    def: null,
    parking: { open: 11, total: 20 },
    amenities: A_REST,
    rating: 3.9,
  },
  {
    id: "scale-ferris",
    name: "Ferris Weigh Station",
    subtitle: "I-45 S · both directions",
    type: "weigh_station",
    coord: { lat: 32.535, lng: -96.668 },
    diesel: null,
    def: null,
    parking: { open: 0, total: 8 },
    amenities: ["scale"],
    rating: 3.0,
  },
  {
    id: "scale-italy",
    name: "Italy Weigh Station",
    subtitle: "I-35E S · MM 394",
    type: "weigh_station",
    coord: { lat: 32.18, lng: -96.88 },
    diesel: null,
    def: null,
    parking: { open: 0, total: 6 },
    amenities: ["scale"],
    rating: 3.0,
  },
  {
    id: "scale-denton",
    name: "Denton Weigh Station",
    subtitle: "I-35 N · MM 467",
    type: "weigh_station",
    coord: { lat: 33.22, lng: -97.13 },
    diesel: null,
    def: null,
    parking: { open: 0, total: 6 },
    amenities: ["scale"],
    rating: 3.0,
  },
  {
    id: "park-lancaster",
    name: "Lancaster Overnight Lot",
    subtitle: "Private · 24 hr gated",
    type: "parking",
    coord: { lat: 32.592, lng: -96.78 },
    diesel: null,
    def: null,
    parking: { open: 27, total: 40 },
    amenities: ["parking", "wifi"],
    rating: 4.0,
  },
  {
    id: "loves-new-braunfels",
    name: "Love's Travel Stop",
    subtitle: "New Braunfels · I-35 Exit 189",
    type: "truck_stop",
    coord: { lat: 29.703, lng: -98.124 },
    diesel: 3.49,
    def: 2.93,
    parking: { open: 5, total: 55 },
    amenities: A_FULL,
    rating: 4.3,
  },
];

function seedReports(): Report[] {
  const now = Date.now();
  const min = 60_000;
  return [
    {
      id: "r1",
      kind: "police",
      coord: { lat: 32.61, lng: -96.7 },
      note: "Median, both directions",
      votes: 18,
      createdAt: now - 12 * min,
      highway: "I-45 S",
    },
    {
      id: "r2",
      kind: "slowdown",
      coord: { lat: 32.2, lng: -96.55 },
      note: "Right lane blocked",
      votes: 41,
      createdAt: now - 7 * min,
      highway: "I-45 S",
    },
    {
      id: "r3",
      kind: "crash",
      coord: { lat: 31.95, lng: -96.34 },
      note: "Shoulder, no lanes down",
      votes: 9,
      createdAt: now - 22 * min,
      highway: "I-45 S",
    },
    {
      id: "r4",
      kind: "construction",
      coord: { lat: 31.48, lng: -96.08 },
      note: "Night work · left lane",
      votes: 27,
      createdAt: now - 54 * min,
      highway: "I-45 S",
    },
    {
      id: "r5",
      kind: "hazard",
      coord: { lat: 32.71, lng: -97.05 },
      note: "Debris in center lane",
      votes: 6,
      createdAt: now - 4 * min,
      highway: "I-30 W",
    },
    {
      id: "r6",
      kind: "camera",
      coord: { lat: 32.76, lng: -96.8 },
      note: "Fixed speed camera",
      votes: 33,
      createdAt: now - 3 * 60 * min,
      highway: "I-35E",
    },
    {
      id: "r7",
      kind: "police",
      coord: { lat: 32.05, lng: -97.12 },
      note: "On-ramp, southbound",
      votes: 14,
      createdAt: now - 18 * min,
      highway: "I-35 S",
    },
    {
      id: "r8",
      kind: "weather",
      coord: { lat: 33.5, lng: -97.14 },
      note: "Heavy rain, standing water",
      votes: 11,
      createdAt: now - 9 * min,
      highway: "I-35 N",
    },
    {
      id: "r9",
      kind: "slowdown",
      coord: { lat: 32.55, lng: -95.95 },
      note: "Rolling backup to Exit 527",
      votes: 20,
      createdAt: now - 15 * min,
      highway: "I-20 E",
    },
    {
      id: "r10",
      kind: "closed",
      coord: { lat: 32.78, lng: -96.92 },
      note: "Ramp closed overnight",
      votes: 8,
      createdAt: now - 40 * min,
      highway: "Loop 12",
    },
    {
      id: "r11",
      kind: "construction",
      coord: { lat: 30.9, lng: -97.4 },
      note: "Concrete pour, 9pm–5am",
      votes: 16,
      createdAt: now - 70 * min,
      highway: "I-35 S",
    },
    {
      id: "r12",
      kind: "hazard",
      coord: { lat: 31.15, lng: -95.72 },
      note: "Blown tire treads",
      votes: 5,
      createdAt: now - 6 * min,
      highway: "I-45 S",
    },
  ];
}

export const SEED_REPORTS: Report[] = seedReports();

type RouteSpec = {
  id: string;
  fromId: string;
  toId: string;
  waypoints: LatLng[];
  highways: string[];
  restrictions: Restriction[];
  traffic: TrafficZone[];
  instructions: Instruction[];
  mph: number;
};

function buildRoute(spec: RouteSpec): Route {
  const polyline = densify(spec.waypoints, 1.05);
  const distanceMi = pathLength(polyline);
  const durationMin = Math.round((distanceMi / spec.mph) * 60);
  return {
    id: spec.id,
    fromId: spec.fromId,
    toId: spec.toId,
    polyline,
    distanceMi,
    durationMin,
    highways: spec.highways,
    restrictions: spec.restrictions,
    traffic: spec.traffic,
    instructions: spec.instructions,
  };
}

export const ROUTES: Route[] = [
  buildRoute({
    id: "to-houston",
    fromId: "origin",
    toId: "houston",
    mph: 61,
    highways: ["I-20 E", "I-45 S"],
    waypoints: [
      ORIGIN,
      { lat: 32.689, lng: -96.78 },
      { lat: 32.68, lng: -96.74 },
      { lat: 32.649, lng: -96.713 },
      { lat: 32.54, lng: -96.68 },
      { lat: 32.329, lng: -96.625 },
      { lat: 32.095, lng: -96.469 },
      { lat: 31.925, lng: -96.32 },
      { lat: 31.725, lng: -96.165 },
      { lat: 31.462, lng: -96.061 },
      { lat: 31.2, lng: -95.92 },
      { lat: 30.95, lng: -95.78 },
      { lat: 30.724, lng: -95.551 },
      { lat: 30.511, lng: -95.5 },
      { lat: 30.312, lng: -95.456 },
      { lat: 30.08, lng: -95.42 },
      { lat: 29.99, lng: -95.4 },
      { lat: 29.7604, lng: -95.3698 },
    ],
    restrictions: [
      { atMi: 14, type: "weigh_open", label: "Ferris weigh station often open" },
      {
        atMi: 38,
        type: "low_bridge",
        label: "Avoided 13'2\" overpass on US-75 frontage",
        heightFt: 13.16,
        avoided: true,
      },
    ],
    traffic: [
      { fromMi: 8, toMi: 18, level: "moderate" },
      { fromMi: 48, toMi: 62, level: "heavy" },
      { fromMi: 210, toMi: 230, level: "moderate" },
    ],
    instructions: [
      { atMi: 0, primary: "Head east", secondary: "I-20 East toward I-45" },
      { atMi: 5.4, primary: "Keep right", secondary: "Merge onto I-45 South toward Houston" },
      { atMi: 18, primary: "Continue south", secondary: "I-45 South · Ennis" },
      { atMi: 48, primary: "Stay in left lanes", secondary: "Backup through Corsicana" },
      { atMi: 96, primary: "Continue on I-45 South", secondary: "Toward Huntsville" },
      { atMi: 170, primary: "Keep left", secondary: "I-45 South · Houston" },
      { atMi: 225, primary: "Take the downtown exits", secondary: "Follow signs for Houston" },
    ],
  }),
  buildRoute({
    id: "to-ftworth",
    fromId: "origin",
    toId: "ftworth",
    mph: 54,
    highways: ["I-20 W", "I-35W N", "I-30 W"],
    waypoints: [
      ORIGIN,
      { lat: 32.69, lng: -96.9 },
      { lat: 32.695, lng: -97.05 },
      { lat: 32.71, lng: -97.18 },
      { lat: 32.74, lng: -97.28 },
      { lat: 32.7555, lng: -97.3308 },
    ],
    restrictions: [
      { atMi: 9, type: "weight", label: "Frontage posted 56,000 lb — stay on I-20" },
    ],
    traffic: [{ fromMi: 12, toMi: 22, level: "moderate" }],
    instructions: [
      { atMi: 0, primary: "Head west", secondary: "I-20 West toward Fort Worth" },
      { atMi: 18, primary: "Keep right", secondary: "I-35W North / I-30 West" },
      { atMi: 26, primary: "Continue on I-30 West", secondary: "Downtown Fort Worth" },
    ],
  }),
  buildRoute({
    id: "to-austin",
    fromId: "origin",
    toId: "austin",
    mph: 63,
    highways: ["I-35E S", "I-35 S"],
    waypoints: [
      ORIGIN,
      { lat: 32.58, lng: -96.86 },
      { lat: 32.4, lng: -96.89 },
      { lat: 32.18, lng: -96.88 },
      { lat: 32.011, lng: -97.115 },
      { lat: 31.8, lng: -97.09 },
      { lat: 31.549, lng: -97.147 },
      { lat: 31.098, lng: -97.343 },
      { lat: 30.633, lng: -97.678 },
      { lat: 30.4, lng: -97.72 },
      { lat: 30.2672, lng: -97.7431 },
    ],
    restrictions: [
      { atMi: 36, type: "weigh_open", label: "Italy scale · southbound" },
      { atMi: 142, type: "grade", label: "Steep grade into Georgetown" },
    ],
    traffic: [
      { fromMi: 70, toMi: 88, level: "moderate" },
      { fromMi: 175, toMi: 195, level: "heavy" },
    ],
    instructions: [
      { atMi: 0, primary: "Head south", secondary: "I-35E South toward Waco" },
      { atMi: 42, primary: "Continue on I-35 South", secondary: "Hillsboro · Waco" },
      { atMi: 96, primary: "Keep left", secondary: "I-35 South · Austin" },
      { atMi: 150, primary: "Stay left through Temple", secondary: "I-35 South" },
      { atMi: 188, primary: "Downtown Austin exits", secondary: "Follow I-35 South" },
    ],
  }),
  buildRoute({
    id: "to-okc",
    fromId: "origin",
    toId: "okc",
    mph: 64,
    highways: ["I-35E N", "I-35 N"],
    waypoints: [
      ORIGIN,
      { lat: 32.78, lng: -96.81 },
      { lat: 32.96, lng: -96.84 },
      { lat: 33.22, lng: -97.13 },
      { lat: 33.626, lng: -97.133 },
      { lat: 33.9, lng: -97.14 },
      { lat: 34.174, lng: -97.145 },
      { lat: 34.6, lng: -97.2 },
      { lat: 35.0, lng: -97.4 },
      { lat: 35.4676, lng: -97.5164 },
    ],
    restrictions: [
      { atMi: 38, type: "weigh_open", label: "Denton weigh station" },
      { atMi: 120, type: "hazmat", label: "Lake Texoma tunnel — no hazmat detour needed on I-35" },
    ],
    traffic: [{ fromMi: 8, toMi: 22, level: "moderate" }],
    instructions: [
      { atMi: 0, primary: "Head north", secondary: "I-35E North toward Denton" },
      { atMi: 28, primary: "Keep left to I-35 North", secondary: "Oklahoma City" },
      { atMi: 92, primary: "Continue on I-35 North", secondary: "Crossing into Oklahoma" },
      { atMi: 170, primary: "Keep right for I-40 / downtown", secondary: "Oklahoma City" },
    ],
  }),
  buildRoute({
    id: "to-waco",
    fromId: "origin",
    toId: "waco",
    mph: 62,
    highways: ["I-35E S", "I-35 S"],
    waypoints: [
      ORIGIN,
      { lat: 32.58, lng: -96.86 },
      { lat: 32.4, lng: -96.89 },
      { lat: 32.18, lng: -96.88 },
      { lat: 32.011, lng: -97.115 },
      { lat: 31.8, lng: -97.09 },
      { lat: 31.5493, lng: -97.1467 },
    ],
    restrictions: [{ atMi: 36, type: "weigh_open", label: "Italy scale · southbound" }],
    traffic: [{ fromMi: 20, toMi: 32, level: "light" }],
    instructions: [
      { atMi: 0, primary: "Head south", secondary: "I-35E South toward Waco" },
      { atMi: 42, primary: "Continue on I-35 South", secondary: "Hillsboro" },
      { atMi: 88, primary: "Take Waco exits", secondary: "I-35 South" },
    ],
  }),
  buildRoute({
    id: "to-tyler",
    fromId: "origin",
    toId: "tyler",
    mph: 62,
    highways: ["I-20 E", "US-69 N"],
    waypoints: [
      ORIGIN,
      { lat: 32.69, lng: -96.7 },
      { lat: 32.66, lng: -96.5 },
      { lat: 32.62, lng: -96.2 },
      { lat: 32.556, lng: -95.863 },
      { lat: 32.5, lng: -95.55 },
      { lat: 32.3513, lng: -95.3011 },
    ],
    restrictions: [
      {
        atMi: 22,
        type: "low_bridge",
        label: "Avoided 12'8\" county road overpass",
        heightFt: 12.67,
        avoided: true,
      },
    ],
    traffic: [{ fromMi: 40, toMi: 55, level: "moderate" }],
    instructions: [
      { atMi: 0, primary: "Head east", secondary: "I-20 East toward Shreveport" },
      { atMi: 48, primary: "Continue on I-20 East", secondary: "Canton" },
      { atMi: 88, primary: "Exit toward Tyler", secondary: "US-69 North" },
    ],
  }),
  buildRoute({
    id: "to-shreveport",
    fromId: "origin",
    toId: "shreveport",
    mph: 63,
    highways: ["I-20 E"],
    waypoints: [
      ORIGIN,
      { lat: 32.69, lng: -96.7 },
      { lat: 32.66, lng: -96.5 },
      { lat: 32.556, lng: -95.863 },
      { lat: 32.5, lng: -95.55 },
      { lat: 32.5, lng: -94.74 },
      { lat: 32.52, lng: -94.2 },
      { lat: 32.5252, lng: -93.7502 },
    ],
    restrictions: [],
    traffic: [{ fromMi: 40, toMi: 58, level: "moderate" }],
    instructions: [
      { atMi: 0, primary: "Head east", secondary: "I-20 East toward Shreveport" },
      { atMi: 90, primary: "Continue on I-20 East", secondary: "Longview · Marshall" },
      { atMi: 175, primary: "Keep right", secondary: "Shreveport downtown exits" },
    ],
  }),
  buildRoute({
    id: "to-sanantonio",
    fromId: "origin",
    toId: "sanantonio",
    mph: 62,
    highways: ["I-35E S", "I-35 S"],
    waypoints: [
      ORIGIN,
      { lat: 32.58, lng: -96.86 },
      { lat: 32.011, lng: -97.115 },
      { lat: 31.549, lng: -97.147 },
      { lat: 31.098, lng: -97.343 },
      { lat: 30.633, lng: -97.678 },
      { lat: 30.2672, lng: -97.7431 },
      { lat: 29.88, lng: -97.92 },
      { lat: 29.703, lng: -98.124 },
      { lat: 29.4241, lng: -98.4936 },
    ],
    restrictions: [
      { atMi: 36, type: "weigh_open", label: "Italy scale · southbound" },
      { atMi: 240, type: "grade", label: "Hill Country grades south of Austin" },
    ],
    traffic: [
      { fromMi: 175, toMi: 195, level: "heavy" },
      { fromMi: 250, toMi: 270, level: "moderate" },
    ],
    instructions: [
      { atMi: 0, primary: "Head south", secondary: "I-35E South toward Austin" },
      { atMi: 96, primary: "Continue on I-35 South", secondary: "Waco · Temple" },
      { atMi: 195, primary: "Stay on I-35 South", secondary: "Through Austin" },
      { atMi: 255, primary: "San Antonio exits", secondary: "I-35 South" },
    ],
  }),
  buildRoute({
    id: "to-alliance",
    fromId: "origin",
    toId: "alliance",
    mph: 55,
    highways: ["I-35E N", "I-635 W", "I-35W N"],
    waypoints: [
      ORIGIN,
      { lat: 32.78, lng: -96.81 },
      { lat: 32.86, lng: -96.85 },
      { lat: 32.89, lng: -97.05 },
      { lat: 32.92, lng: -97.2 },
      { lat: 32.9765, lng: -97.318 },
    ],
    restrictions: [],
    traffic: [{ fromMi: 6, toMi: 16, level: "moderate" }],
    instructions: [
      { atMi: 0, primary: "Head north", secondary: "I-35E North" },
      { atMi: 14, primary: "Keep left onto I-635 West", secondary: "Toward DFW / Alliance" },
      { atMi: 28, primary: "Exit toward Alliance", secondary: "Haslet / BNSF yard" },
    ],
  }),
  buildRoute({
    id: "to-lancaster",
    fromId: "origin",
    toId: "lancaster-dc",
    mph: 48,
    highways: ["I-20 E", "I-45 S"],
    waypoints: [
      ORIGIN,
      { lat: 32.689, lng: -96.78 },
      { lat: 32.65, lng: -96.76 },
      { lat: 32.592, lng: -96.756 },
    ],
    restrictions: [],
    traffic: [{ fromMi: 2, toMi: 8, level: "light" }],
    instructions: [
      { atMi: 0, primary: "Head east", secondary: "I-20 East toward I-45" },
      { atMi: 4.5, primary: "Keep right", secondary: "I-45 South · Lancaster" },
      { atMi: 9, primary: "Exit toward Logistics Park", secondary: "Local roads" },
    ],
  }),
  buildRoute({
    id: "to-houston-port",
    fromId: "origin",
    toId: "houston-port",
    mph: 60,
    highways: ["I-20 E", "I-45 S", "TX-146"],
    waypoints: [
      ORIGIN,
      { lat: 32.649, lng: -96.713 },
      { lat: 32.329, lng: -96.625 },
      { lat: 31.725, lng: -96.165 },
      { lat: 30.724, lng: -95.551 },
      { lat: 29.99, lng: -95.4 },
      { lat: 29.76, lng: -95.2 },
      { lat: 29.737, lng: -95.021 },
    ],
    restrictions: [
      { atMi: 14, type: "weigh_open", label: "Ferris weigh station often open" },
      { atMi: 250, type: "weight", label: "Port access roads posted 80,000 lb" },
    ],
    traffic: [
      { fromMi: 48, toMi: 62, level: "heavy" },
      { fromMi: 230, toMi: 250, level: "moderate" },
    ],
    instructions: [
      { atMi: 0, primary: "Head east then south", secondary: "I-20 East to I-45 South" },
      { atMi: 5.4, primary: "Merge onto I-45 South", secondary: "Houston" },
      { atMi: 240, primary: "Keep east toward the channel", secondary: "Barbours Cut / Bayport" },
    ],
  }),
  buildRoute({
    id: "to-dfw-cargo",
    fromId: "origin",
    toId: "dfw-cargo",
    mph: 50,
    highways: ["I-35E N", "TX-183 W"],
    waypoints: [
      ORIGIN,
      { lat: 32.78, lng: -96.81 },
      { lat: 32.84, lng: -96.86 },
      { lat: 32.88, lng: -96.95 },
      { lat: 32.896, lng: -97.038 },
    ],
    restrictions: [
      { atMi: 12, type: "low_bridge", label: "Airport service road 13'4\" — stay on 183", heightFt: 13.33, avoided: true },
    ],
    traffic: [{ fromMi: 4, toMi: 14, level: "moderate" }],
    instructions: [
      { atMi: 0, primary: "Head north", secondary: "I-35E North" },
      { atMi: 10, primary: "Keep left onto 183 West", secondary: "DFW Airport" },
      { atMi: 18, primary: "Cargo East ramps", secondary: "Air freight complex" },
    ],
  }),
];

export const ROUTE_BY_DEST: Record<string, string> = Object.fromEntries(
  ROUTES.map((r) => [r.toId, r.id]),
);

export function placeById(id: string): Place | undefined {
  return PLACES.find((p) => p.id === id);
}

export function routeById(id: string): Route | undefined {
  return ROUTES.find((r) => r.id === id);
}

export function facilityById(id: string): Facility | undefined {
  return FACILITIES.find((f) => f.id === id);
}

export const REPORT_META: Record<
  Report["kind"],
  { label: string; hint: string; className: string }
> = {
  police: { label: "Police", hint: "Seen a cruiser", className: "report-police" },
  crash: { label: "Crash", hint: "Accident on road", className: "report-crash" },
  hazard: { label: "Hazard", hint: "Debris or stall", className: "report-hazard" },
  construction: { label: "Work zone", hint: "Cones and crews", className: "report-work" },
  slowdown: { label: "Slowdown", hint: "Traffic stacking", className: "report-slow" },
  camera: { label: "Camera", hint: "Speed or red light", className: "report-camera" },
  weather: { label: "Weather", hint: "Rain, ice, wind", className: "report-wx" },
  closed: { label: "Closed", hint: "Road or ramp shut", className: "report-closed" },
};

export const AMENITY_LABEL: Record<Amenity, string> = {
  showers: "Showers",
  food: "Food",
  scale: "Scale",
  def: "DEF",
  wash: "Wash",
  parking: "Parking",
  wifi: "Wi-Fi",
  repair: "Repair",
};

export const POSTED_LIMIT = 70;
